### ISSUE TITLE
How to chat?

### ISSUE THREAD

**Issue by PaulWoitaschek** [cycneuramus/signal-aichat#6]
Maybe I'm missing something obvious here but I can't get this running.

I want to use only the openai integration.

My compose file looks like this:
```docker-compose
version: "3.9"

services:
  signald:
    image: registry.gitlab.com/signald/signald
    container_name: signal-aichat-signald
    restart: unless-stopped
    volumes:
      - ./signald:/signald

  bot:
    image: ghcr.io/cycneuramus/signal-aichat
    container_name: signal-aichat-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./signald:/signald
```

I had to remove the user: 1000, 1000 else it was showing errors when communicating with the socket

My .env file is this:
```.env
SIGNAL_PHONE_NUMBER=+491xxxxxxx
OPENAI_API_KEY=a-i-i
DEFAULT_MODEL=gpt
DISABLED_MODELS=bing llama
OPENAI_API_BASE=https://api.openai.com/v1
```

After following the steps, the signald container seems to work and logs when I send a message to myself:

```
Updating permissions on /signald (for info see "migrating from versions before 0.18.0" on https://signald.org/articles/install/docker/)

10:51:26.214 [main] INFO  io.finn.signald.Main - all data migrations complete

10:51:26.218 [main] INFO  io.finn.signald.Main - Binding to socket /signald/signald.sock

10:51:26.283 [main] INFO  io.finn.signald.Main - Started signald 0.23.2

10:51:27.683 [subscribe] INFO  manager-[redacted 33]979 - Created a manager for [redacted 33]979

10:51:28.693 [[redacted 33]979-receiver] INFO  manager-[redacted 33]979 - received sent message transcript from device 2

10:51:46.557 [[redacted 33]979-receiver] INFO  manager-[redacted 33]979 - received sent message transcript from device 2
```

However the chatbot itself doesn't seem to do anything:

It's logs show:
```
Traceback (most recent call last):

  File "/home/signal-aichat/signal-aichat.py", line 175, in <module>

    anyio.run(main)

  File "/home/signal-aichat/.local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run

    return asynclib.run(func, *args, **backend_options)

  File "/home/signal-aichat/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run

    return native_run(wrapper(), debug=debug)

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete

    return future.result()

  File "/home/signal-aichat/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper

    return await func(*args)

  File "/home/signal-aichat/signal-aichat.py", line 164, in main

    async with Bot(

  File "/home/signal-aichat/.local/lib/python3.10/site-packages/semaphore/bot.py", line 167, in __aenter__

    self._send_socket = await Socket(self._username,

  File "/home/signal-aichat/.local/lib/python3.10/site-packages/semaphore/socket.py", line 51, in __aenter__

    self._socket = await (await anyio.connect_unix(sockets[i])).__aenter__()

  File "/home/signal-aichat/.local/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 251, in connect_unix

    return await get_asynclib().connect_unix(path)

  File "/home/signal-aichat/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1706, in connect_unix

    raw_socket.connect(path)

ConnectionRefusedError: [Errno 111] Connection refused

2023-05-14 10:51:27,484 bot: [INFO] Connected to socket (/signald/signald.sock)

2023-05-14 10:51:27,484 bot: [INFO] Handler <ai> registered ('')

2023-05-14 10:51:27,485 bot: [INFO] Bot started

2023-05-14 10:51:27,485 bot: [INFO] Connected to socket (/signald/signald.sock)

2023-05-14 10:51:27,485 bot: [INFO] Bot attempted to subscribe to +********525

2023-05-14 10:51:27,485 bot: [INFO] Job queue started
```

The readme is a bit vague in the final steps:

> And start chatting.

So I assume that I have to talk to it using `Note to Self` but that's not working.
Am I missing something obvious here?

**Comment by cycneuramus** [comment]
I should definitely document this, but I don't actually know if this is supposed to work using the same Signal number to both send and receive. It's probable that sending a message to your own number works differently inside Signal than sending a message to someone else. I use a secondary phone number to register a separate Signal account for the bot and that works fine.
